baseURL = "https://shengchao.vip/"
languageCode = "zh-cn"
title = "胜超日常"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  author = "叶胜超"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true

[menu]

  [[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 2