baseURL = "https://shengchao.vip/"
languageCode = "zh-cn"
title = "胜超日常"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  author = "胜超日常"
  defaultTheme = "auto"
  # 显示阅读时间
  ShowReadingTime = true
  # 文章底部显示分享按钮
  ShowShareButtons = true
  # 显示字数统计
  ShowWordCount = true
  # 显示上一篇/下一篇导航
  ShowPostNavLinks = true
  # 代码块一键复制按钮
  ShowCodeCopyButtons = true
  # 文章顶部显示面包屑导航
  ShowBreadCrumbs = true
  # 去掉底部版权
  hideFooter = true
  # 允许支持HTML
  [markup.goldmark.renderer]
  unsafe = true

[menu]

  [[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

  
  [[menu.main]]
  name = "归档"
  url = "/archives/"
  weight = 2

[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 3

[[menu.main]]
  name = "搜索"
  url = "/search/"
  weight = 4
  # 必须要加这个，才能搜索到
  [outputs]
  home = ["HTML", "RSS", "JSON"]
  
  

[[menu.main]]
  name = "友情链接"
  url = "/links/"
  weight = 5
  
  
  
  
  